/**
 * ISO 3166-1 alpha-2 to numeric code mapping.
 * Used by WorldMap to match Cloudflare's alpha-2 country codes
 * to world-atlas TopoJSON numeric IDs.
 *
 * Also provides alpha-2 to full English name for display.
 */

// alpha-2 -> [numeric, English name]
const COUNTRIES: Record<string, [string, string]> = {
  AF: ["004", "Afghanistan"],
  AL: ["008", "Albania"],
  DZ: ["012", "Algeria"],
  AS: ["016", "American Samoa"],
  AD: ["020", "Andorra"],
  AO: ["024", "Angola"],
  AG: ["028", "Antigua and Barbuda"],
  AR: ["032", "Argentina"],
  AM: ["051", "Armenia"],
  AU: ["036", "Australia"],
  AT: ["040", "Austria"],
  AZ: ["031", "Azerbaijan"],
  BS: ["044", "Bahamas"],
  BH: ["048", "Bahrain"],
  BD: ["050", "Bangladesh"],
  BB: ["052", "Barbados"],
  BY: ["112", "Belarus"],
  BE: ["056", "Belgium"],
  BZ: ["084", "Belize"],
  BJ: ["204", "Benin"],
  BT: ["064", "Bhutan"],
  BO: ["068", "Bolivia"],
  BA: ["070", "Bosnia and Herzegovina"],
  BW: ["072", "Botswana"],
  BR: ["076", "Brazil"],
  BN: ["096", "Brunei"],
  BG: ["100", "Bulgaria"],
  BF: ["854", "Burkina Faso"],
  BI: ["108", "Burundi"],
  KH: ["116", "Cambodia"],
  CM: ["120", "Cameroon"],
  CA: ["124", "Canada"],
  CV: ["132", "Cape Verde"],
  CF: ["140", "Central African Republic"],
  TD: ["148", "Chad"],
  CL: ["152", "Chile"],
  CN: ["156", "China"],
  CO: ["170", "Colombia"],
  KM: ["174", "Comoros"],
  CG: ["178", "Congo"],
  CD: ["180", "DR Congo"],
  CR: ["188", "Costa Rica"],
  CI: ["384", "Ivory Coast"],
  HR: ["191", "Croatia"],
  CU: ["192", "Cuba"],
  CY: ["196", "Cyprus"],
  CZ: ["203", "Czechia"],
  DK: ["208", "Denmark"],
  DJ: ["262", "Djibouti"],
  DM: ["212", "Dominica"],
  DO: ["214", "Dominican Republic"],
  EC: ["218", "Ecuador"],
  EG: ["818", "Egypt"],
  SV: ["222", "El Salvador"],
  GQ: ["226", "Equatorial Guinea"],
  ER: ["232", "Eritrea"],
  EE: ["233", "Estonia"],
  SZ: ["748", "Eswatini"],
  ET: ["231", "Ethiopia"],
  FJ: ["242", "Fiji"],
  FI: ["246", "Finland"],
  FR: ["250", "France"],
  GA: ["266", "Gabon"],
  GM: ["270", "Gambia"],
  GE: ["268", "Georgia"],
  DE: ["276", "Germany"],
  GH: ["288", "Ghana"],
  GR: ["300", "Greece"],
  GD: ["308", "Grenada"],
  GT: ["320", "Guatemala"],
  GN: ["324", "Guinea"],
  GW: ["624", "Guinea-Bissau"],
  GY: ["328", "Guyana"],
  HT: ["332", "Haiti"],
  HN: ["340", "Honduras"],
  HK: ["344", "Hong Kong"],
  HU: ["348", "Hungary"],
  IS: ["352", "Iceland"],
  IN: ["356", "India"],
  ID: ["360", "Indonesia"],
  IR: ["364", "Iran"],
  IQ: ["368", "Iraq"],
  IE: ["372", "Ireland"],
  IL: ["376", "Israel"],
  IT: ["380", "Italy"],
  JM: ["388", "Jamaica"],
  JP: ["392", "Japan"],
  JO: ["400", "Jordan"],
  KZ: ["398", "Kazakhstan"],
  KE: ["404", "Kenya"],
  KI: ["296", "Kiribati"],
  KP: ["408", "North Korea"],
  KR: ["410", "South Korea"],
  KW: ["414", "Kuwait"],
  KG: ["417", "Kyrgyzstan"],
  LA: ["418", "Laos"],
  LV: ["428", "Latvia"],
  LB: ["422", "Lebanon"],
  LS: ["426", "Lesotho"],
  LR: ["430", "Liberia"],
  LY: ["434", "Libya"],
  LI: ["438", "Liechtenstein"],
  LT: ["440", "Lithuania"],
  LU: ["442", "Luxembourg"],
  MO: ["446", "Macao"],
  MG: ["450", "Madagascar"],
  MW: ["454", "Malawi"],
  MY: ["458", "Malaysia"],
  MV: ["462", "Maldives"],
  ML: ["466", "Mali"],
  MT: ["470", "Malta"],
  MH: ["584", "Marshall Islands"],
  MR: ["478", "Mauritania"],
  MU: ["480", "Mauritius"],
  MX: ["484", "Mexico"],
  FM: ["583", "Micronesia"],
  MD: ["498", "Moldova"],
  MC: ["492", "Monaco"],
  MN: ["496", "Mongolia"],
  ME: ["499", "Montenegro"],
  MA: ["504", "Morocco"],
  MZ: ["508", "Mozambique"],
  MM: ["104", "Myanmar"],
  NA: ["516", "Namibia"],
  NR: ["520", "Nauru"],
  NP: ["524", "Nepal"],
  NL: ["528", "Netherlands"],
  NZ: ["554", "New Zealand"],
  NI: ["558", "Nicaragua"],
  NE: ["562", "Niger"],
  NG: ["566", "Nigeria"],
  MK: ["807", "North Macedonia"],
  NO: ["578", "Norway"],
  OM: ["512", "Oman"],
  PK: ["586", "Pakistan"],
  PW: ["585", "Palau"],
  PS: ["275", "Palestine"],
  PA: ["591", "Panama"],
  PG: ["598", "Papua New Guinea"],
  PY: ["600", "Paraguay"],
  PE: ["604", "Peru"],
  PH: ["608", "Philippines"],
  PL: ["616", "Poland"],
  PT: ["620", "Portugal"],
  QA: ["634", "Qatar"],
  RO: ["642", "Romania"],
  RU: ["643", "Russia"],
  RW: ["646", "Rwanda"],
  KN: ["659", "Saint Kitts and Nevis"],
  LC: ["662", "Saint Lucia"],
  VC: ["670", "St Vincent and Grenadines"],
  WS: ["882", "Samoa"],
  SM: ["674", "San Marino"],
  ST: ["678", "Sao Tome and Principe"],
  SA: ["682", "Saudi Arabia"],
  SN: ["686", "Senegal"],
  RS: ["688", "Serbia"],
  SC: ["690", "Seychelles"],
  SL: ["694", "Sierra Leone"],
  SG: ["702", "Singapore"],
  SK: ["703", "Slovakia"],
  SI: ["705", "Slovenia"],
  SB: ["090", "Solomon Islands"],
  SO: ["706", "Somalia"],
  ZA: ["710", "South Africa"],
  SS: ["728", "South Sudan"],
  ES: ["724", "Spain"],
  LK: ["144", "Sri Lanka"],
  SD: ["729", "Sudan"],
  SR: ["740", "Suriname"],
  SE: ["752", "Sweden"],
  CH: ["756", "Switzerland"],
  SY: ["760", "Syria"],
  TW: ["158", "Taiwan"],
  TJ: ["762", "Tajikistan"],
  TZ: ["834", "Tanzania"],
  TH: ["764", "Thailand"],
  TL: ["626", "Timor-Leste"],
  TG: ["768", "Togo"],
  TO: ["776", "Tonga"],
  TT: ["780", "Trinidad and Tobago"],
  TN: ["788", "Tunisia"],
  TR: ["792", "Turkey"],
  TM: ["795", "Turkmenistan"],
  TV: ["798", "Tuvalu"],
  UG: ["800", "Uganda"],
  UA: ["804", "Ukraine"],
  AE: ["784", "United Arab Emirates"],
  GB: ["826", "United Kingdom"],
  US: ["840", "United States"],
  UY: ["858", "Uruguay"],
  UZ: ["860", "Uzbekistan"],
  VU: ["548", "Vanuatu"],
  VA: ["336", "Vatican City"],
  VE: ["862", "Venezuela"],
  VN: ["704", "Vietnam"],
  YE: ["887", "Yemen"],
  ZM: ["894", "Zambia"],
  ZW: ["716", "Zimbabwe"],
  XK: ["383", "Kosovo"],
  XX: ["000", "Unknown"],
  T1: ["000", "Tor Exit Node"],
};

/** Get ISO numeric code from alpha-2. Returns undefined if not found. */
export function alpha2ToNumeric(code: string): string | undefined {
  return COUNTRIES[code.toUpperCase()]?.[0];
}

/** Get English country name from alpha-2. Returns the code itself if not found. */
export function alpha2ToName(code: string): string {
  return COUNTRIES[code.toUpperCase()]?.[1] ?? code;
}

export default COUNTRIES;
